apiVersion: v1
kind: Service
metadata:
  name: loco-python-app-service
  namespace: loco-assessment
  labels:
    app: loco-python-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: loco-python-app
