apiVersion: apps/v1
kind: Deployment
metadata:
  name: loco-python-app-deployment
  namespace: loco-assessment
  labels:
    app: loco-python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loco-python-app
  template:
    metadata:
      labels:
        app: loco-python-app
    spec:
      containers:
        - name: loco-python-app
          image: nagarajjayitech/loco-assessment:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
